<?php

/**
 * BaseExtraReserved
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_extra
 * @property integer $id_booking
 * @property integer $id_activity
 * @property integer $log_price
 * @property Extra $Extra
 * @property Booking $Booking
 * @property Activity $Activity
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method integer       getIdExtra()     Returns the current record's "id_extra" value
 * @method integer       getIdBooking()   Returns the current record's "id_booking" value
 * @method integer       getIdActivity()  Returns the current record's "id_activity" value
 * @method integer       getLogPrice()    Returns the current record's "log_price" value
 * @method Extra         getExtra()       Returns the current record's "Extra" value
 * @method Booking       getBooking()     Returns the current record's "Booking" value
 * @method Activity      getActivity()    Returns the current record's "Activity" value
 * @method ExtraReserved setId()          Sets the current record's "id" value
 * @method ExtraReserved setIdExtra()     Sets the current record's "id_extra" value
 * @method ExtraReserved setIdBooking()   Sets the current record's "id_booking" value
 * @method ExtraReserved setIdActivity()  Sets the current record's "id_activity" value
 * @method ExtraReserved setLogPrice()    Sets the current record's "log_price" value
 * @method ExtraReserved setExtra()       Sets the current record's "Extra" value
 * @method ExtraReserved setBooking()     Sets the current record's "Booking" value
 * @method ExtraReserved setActivity()    Sets the current record's "Activity" value
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExtraReserved extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('extra_reserved');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('id_extra', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_booking', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_activity', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('log_price', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Extra', array(
             'local' => 'id_extra',
             'foreign' => 'id'));

        $this->hasOne('Booking', array(
             'local' => 'id_booking',
             'foreign' => 'id',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasOne('Activity', array(
             'local' => 'id_activity',
             'foreign' => 'id'));
    }
}