<?php

/**
 * BaseReview
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id_client
 * @property string $description
 * @property string $image
 * @property string $country
 * @property boolean $valide
 * @property boolean $del
 * @property User $User
 * 
 * @method integer getIdClient()    Returns the current record's "id_client" value
 * @method string  getDescription() Returns the current record's "description" value
 * @method string  getImage()       Returns the current record's "image" value
 * @method string  getCountry()     Returns the current record's "country" value
 * @method boolean getValide()      Returns the current record's "valide" value
 * @method boolean getDel()         Returns the current record's "del" value
 * @method User    getUser()        Returns the current record's "User" value
 * @method Review  setIdClient()    Sets the current record's "id_client" value
 * @method Review  setDescription() Sets the current record's "description" value
 * @method Review  setImage()       Sets the current record's "image" value
 * @method Review  setCountry()     Sets the current record's "country" value
 * @method Review  setValide()      Sets the current record's "valide" value
 * @method Review  setDel()         Sets the current record's "del" value
 * @method Review  setUser()        Sets the current record's "User" value
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReview extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('review');
        $this->hasColumn('id_client', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', 63535, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 63535,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('valide', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('del', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'id_client',
             'foreign' => 'id'));
    }
}