<?php

/**
 * BasePartners
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $adress
 * @property string $cp
 * @property string $city
 * @property string $country
 * @property string $phone
 * @property string $contact_name
 * @property Doctrine_Collection $BonusPartners
 * 
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getAdress()        Returns the current record's "adress" value
 * @method string              getCp()            Returns the current record's "cp" value
 * @method string              getCity()          Returns the current record's "city" value
 * @method string              getCountry()       Returns the current record's "country" value
 * @method string              getPhone()         Returns the current record's "phone" value
 * @method string              getContactName()   Returns the current record's "contact_name" value
 * @method Doctrine_Collection getBonusPartners() Returns the current record's "BonusPartners" collection
 * @method Partners            setName()          Sets the current record's "name" value
 * @method Partners            setAdress()        Sets the current record's "adress" value
 * @method Partners            setCp()            Sets the current record's "cp" value
 * @method Partners            setCity()          Sets the current record's "city" value
 * @method Partners            setCountry()       Sets the current record's "country" value
 * @method Partners            setPhone()         Sets the current record's "phone" value
 * @method Partners            setContactName()   Sets the current record's "contact_name" value
 * @method Partners            setBonusPartners() Sets the current record's "BonusPartners" collection
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePartners extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('partners');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('adress', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('cp', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('contact_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BonusPartner as BonusPartners', array(
             'local' => 'id',
             'foreign' => 'id_partner'));
    }
}