<?php

/**
 * BaseLanguesMoney
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $langues_id
 * @property integer $money_id
 * @property Langues $Langues
 * @property Money $Money
 * 
 * @method integer      getLanguesId()  Returns the current record's "langues_id" value
 * @method integer      getMoneyId()    Returns the current record's "money_id" value
 * @method Langues      getLangues()    Returns the current record's "Langues" value
 * @method Money        getMoney()      Returns the current record's "Money" value
 * @method LanguesMoney setLanguesId()  Sets the current record's "langues_id" value
 * @method LanguesMoney setMoneyId()    Sets the current record's "money_id" value
 * @method LanguesMoney setLangues()    Sets the current record's "Langues" value
 * @method LanguesMoney setMoney()      Sets the current record's "Money" value
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLanguesMoney extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('langues_money');
        $this->hasColumn('langues_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('money_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Langues', array(
             'local' => 'langues_id',
             'foreign' => 'id'));

        $this->hasOne('Money', array(
             'local' => 'money_id',
             'foreign' => 'id'));
    }
}