<?php

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $description
 * @property integer $id_activity
 * @property integer $id_client
 * @property boolean $valide
 * @property boolean $del
 * @property User $User
 * @property Activity $Activity
 * 
 * @method string   getDescription() Returns the current record's "description" value
 * @method integer  getIdActivity()  Returns the current record's "id_activity" value
 * @method integer  getIdClient()    Returns the current record's "id_client" value
 * @method boolean  getValide()      Returns the current record's "valide" value
 * @method boolean  getDel()         Returns the current record's "del" value
 * @method User     getUser()        Returns the current record's "User" value
 * @method Activity getActivity()    Returns the current record's "Activity" value
 * @method Comment  setDescription() Sets the current record's "description" value
 * @method Comment  setIdActivity()  Sets the current record's "id_activity" value
 * @method Comment  setIdClient()    Sets the current record's "id_client" value
 * @method Comment  setValide()      Sets the current record's "valide" value
 * @method Comment  setDel()         Sets the current record's "del" value
 * @method Comment  setUser()        Sets the current record's "User" value
 * @method Comment  setActivity()    Sets the current record's "Activity" value
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('description', 'string', 65536, array(
             'type' => 'string',
             'length' => 65536,
             ));
        $this->hasColumn('id_activity', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('id_client', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('valide', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('del', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'id_client',
             'foreign' => 'id'));

        $this->hasOne('Activity', array(
             'local' => 'id_activity',
             'foreign' => 'id'));
    }
}