<?php

/**
 * BaseLangues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $iso
 * @property string $country
 * @property Doctrine_Collection $Money
 * @property Doctrine_Collection $LanguesMoney
 * @property Slider $Slider
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getIso()          Returns the current record's "iso" value
 * @method string              getCountry()      Returns the current record's "country" value
 * @method Doctrine_Collection getMoney()        Returns the current record's "Money" collection
 * @method Doctrine_Collection getLanguesMoney() Returns the current record's "LanguesMoney" collection
 * @method Slider              getSlider()       Returns the current record's "Slider" value
 * @method Langues             setId()           Sets the current record's "id" value
 * @method Langues             setIso()          Sets the current record's "iso" value
 * @method Langues             setCountry()      Sets the current record's "country" value
 * @method Langues             setMoney()        Sets the current record's "Money" collection
 * @method Langues             setLanguesMoney() Sets the current record's "LanguesMoney" collection
 * @method Langues             setSlider()       Sets the current record's "Slider" value
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLangues extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('langues');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('iso', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Money', array(
             'refClass' => 'LanguesMoney',
             'local' => 'langues_id',
             'foreign' => 'money_id'));

        $this->hasMany('LanguesMoney', array(
             'local' => 'id',
             'foreign' => 'langues_id'));

        $this->hasOne('Slider', array(
             'local' => 'id',
             'foreign' => 'lang'));
    }
}