<?php

/**
 * BaseExtraActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_activity
 * @property integer $id_extra
 * @property Extra $Extra
 * @property Activity $Activity
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method integer       getIdActivity()  Returns the current record's "id_activity" value
 * @method integer       getIdExtra()     Returns the current record's "id_extra" value
 * @method Extra         getExtra()       Returns the current record's "Extra" value
 * @method Activity      getActivity()    Returns the current record's "Activity" value
 * @method ExtraActivity setId()          Sets the current record's "id" value
 * @method ExtraActivity setIdActivity()  Sets the current record's "id_activity" value
 * @method ExtraActivity setIdExtra()     Sets the current record's "id_extra" value
 * @method ExtraActivity setExtra()       Sets the current record's "Extra" value
 * @method ExtraActivity setActivity()    Sets the current record's "Activity" value
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExtraActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('extra_activity');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('id_activity', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('id_extra', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Extra', array(
             'local' => 'id_extra',
             'foreign' => 'id'));

        $this->hasOne('Activity', array(
             'local' => 'id_activity',
             'foreign' => 'id'));
    }
}