<?php

/**
 * BaseSlider
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $image
 * @property integer $id_activity
 * @property string $title
 * @property integer $position
 * @property boolean $active
 * @property integer $lang
 * @property Activity $Activity
 * @property Doctrine_Collection $Langues
 * 
 * @method string              getImage()       Returns the current record's "image" value
 * @method integer             getIdActivity()  Returns the current record's "id_activity" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method integer             getPosition()    Returns the current record's "position" value
 * @method boolean             getActive()      Returns the current record's "active" value
 * @method integer             getLang()        Returns the current record's "lang" value
 * @method Activity            getActivity()    Returns the current record's "Activity" value
 * @method Doctrine_Collection getLangues()     Returns the current record's "Langues" collection
 * @method Slider              setImage()       Sets the current record's "image" value
 * @method Slider              setIdActivity()  Sets the current record's "id_activity" value
 * @method Slider              setTitle()       Sets the current record's "title" value
 * @method Slider              setPosition()    Sets the current record's "position" value
 * @method Slider              setActive()      Sets the current record's "active" value
 * @method Slider              setLang()        Sets the current record's "lang" value
 * @method Slider              setActivity()    Sets the current record's "Activity" value
 * @method Slider              setLangues()     Sets the current record's "Langues" collection
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlider extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slider');
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('id_activity', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('lang', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Activity', array(
             'local' => 'id_activity',
             'foreign' => 'id'));

        $this->hasMany('Langues', array(
             'local' => 'lang',
             'foreign' => 'id'));
    }
}