<?php

/**
 * BaseHighlightActivity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $number
 * @property integer $activity
 * @property string $title
 * @property string $title_blue
 * @property string $description
 * 
 * @method integer           getNumber()      Returns the current record's "number" value
 * @method integer           getActivity()    Returns the current record's "activity" value
 * @method string            getTitle()       Returns the current record's "title" value
 * @method string            getTitleBlue()   Returns the current record's "title_blue" value
 * @method string            getDescription() Returns the current record's "description" value
 * @method HighlightActivity setNumber()      Sets the current record's "number" value
 * @method HighlightActivity setActivity()    Sets the current record's "activity" value
 * @method HighlightActivity setTitle()       Sets the current record's "title" value
 * @method HighlightActivity setTitleBlue()   Sets the current record's "title_blue" value
 * @method HighlightActivity setDescription() Sets the current record's "description" value
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHighlightActivity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('highlight_activity');
        $this->hasColumn('number', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('activity', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title_blue', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 65535, array(
             'type' => 'string',
             'length' => 65535,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'title_blue',
              2 => 'description',
              3 => 'activity',
             ),
             ));
        $this->actAs($i18n0);
    }
}