<?php

/**
 * BaseExtra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_category
 * @property string $name
 * @property text $description
 * @property integer $price
 * @property boolean $del
 * @property ExtraCategory $ExtraCategory
 * @property Doctrine_Collection $ExtraActivity
 * @property Doctrine_Collection $ExtraReserved
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getIdCategory()    Returns the current record's "id_category" value
 * @method string              getName()          Returns the current record's "name" value
 * @method text                getDescription()   Returns the current record's "description" value
 * @method integer             getPrice()         Returns the current record's "price" value
 * @method boolean             getDel()           Returns the current record's "del" value
 * @method ExtraCategory       getExtraCategory() Returns the current record's "ExtraCategory" value
 * @method Doctrine_Collection getExtraActivity() Returns the current record's "ExtraActivity" collection
 * @method Doctrine_Collection getExtraReserved() Returns the current record's "ExtraReserved" collection
 * @method Extra               setId()            Sets the current record's "id" value
 * @method Extra               setIdCategory()    Sets the current record's "id_category" value
 * @method Extra               setName()          Sets the current record's "name" value
 * @method Extra               setDescription()   Sets the current record's "description" value
 * @method Extra               setPrice()         Sets the current record's "price" value
 * @method Extra               setDel()           Sets the current record's "del" value
 * @method Extra               setExtraCategory() Sets the current record's "ExtraCategory" value
 * @method Extra               setExtraActivity() Sets the current record's "ExtraActivity" collection
 * @method Extra               setExtraReserved() Sets the current record's "ExtraReserved" collection
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExtra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('extra');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('id_category', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('price', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('del', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ExtraCategory', array(
             'local' => 'id_category',
             'foreign' => 'id'));

        $this->hasMany('ExtraActivity', array(
             'local' => 'id',
             'foreign' => 'id_extra'));

        $this->hasMany('ExtraReserved', array(
             'local' => 'id',
             'foreign' => 'id_extra'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'name',
              1 => 'description',
              2 => 'price',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'name',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($i18n0);
    }
}