<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/08 16:05:39

return array(
'stag' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=stag',
  'username' => 'root',
  'password' => 'root',
  'name' => 'stag',
)),);
