<?php
// auto-generated by sfCacheConfigHandler
// date: 2011/12/09 12:12:08
$this->addCache($moduleName, '_header', array('withLayout' => true, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => true, 'lifeTime' => 3600, 'clientLifeTime' => 3600, 'contextual' => false, 'vary' => array ()));

