<?php
// auto-generated by sfCacheConfigHandler
// date: 2011/12/12 15:14:47
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => true, 'lifeTime' => 3600, 'clientLifeTime' => 3600, 'contextual' => false, 'vary' => array ()));

