<?php

/**
 * ActivityCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityCategory');
    }
    
    public function getAllWithVisible()
    {
      $q = Doctrine_Query::create()
          ->from('ActivityCategory a')
          ->leftJoin('a.Translation t')
          ->where('a.del = false')
          ->orderBy('t.name');
      return $q->execute();
    }
    
    public function getAll()
    {
      $q = Doctrine_Query::create()
          ->from('ActivityCategory a')
          ->leftJoin('a.Translation t')
          ->innerJoin('a.Activity aa')
          ->where('a.del = false')
          ->andWhere('aa.del = false')
          ->orderBy('t.name');
      return $q->execute();
    }
    
    public function findCategory($lang, $slug)
    {
      $q = $this->createQuery('c')
              ->leftJoin('c.Translation t')
              ->where('t.lang = ?', $lang)
              ->andWhere('t.slug = ?', $slug)
              ->andWhere('t.visible = true');
      return $q->fetchOne();
    }
}