<?php

/**
 * ActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Activity');
    }
    
    public function getAjaxResults($search)
    {
        $q = $this->createQuery('a')
                ->leftJoin('a.Translation t')
                ->select('a.id, t.name, t.slug')
                ->where('t.name LIKE ?', '%'.$search.'%');
//        echo $q->getSqlQuery();
        return $q->execute();
    }
    
    public function findOneBySlug($slug)
    {
      $q = $this->createQuery('a')
        ->leftJoin('a.Translation t')
        ->andWhere('t.slug = ?', $slug)
        ->andWhere('t.visible = true');
      return $q->fetchOne();
    }
    
    public function findActivity($lang, $slug)
    {
      $q = $this->createQuery('a')
              ->leftJoin('a.Translation t')
              ->where('t.lang = ?', $lang)
              ->andWhere('t.slug = ?', $slug)
              ->andWhere('t.visible = true');
      return $q->fetchOne();
    }
    
    public function findActivityById($lang, $id)
    {
      $q = $this->createQuery('a')
              ->leftJoin('a.Translation t')
              ->where('t.lang = ?', $lang)
              ->andWhere('a.id = ?', $id)
              ->andWhere('t.visible = true');
      return $q->fetchOne();
    }
    
    public function findActivityByCategory($lang, $id)
    {
      $q = $this->createQuery('a')
              ->leftJoin('a.Translation t')
              ->where('t.lang = ?', $lang)
              ->andWhere('a.id_category = ?', $id)
              ->andWhere('t.visible = true');
      return $q->execute();
    }
}