<?php

/**
 * ActivityPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActivityPriceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActivityPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActivityPrice');
    }
}