<?php

/**
 * BonusPartnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BonusPartnerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BonusPartnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BonusPartner');
    }
}