<?php

/**
 * BookingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BookingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BookingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Booking');
    }
    
    public function getByIdPlanner($id)
    {
        $q = $this->createQuery('b')
                  ->leftJoin('b.Planner p')
                  ->leftJoin('p.User c')
                  ->leftJoin('b.Activity a')
                  ->leftJoin('a.Translation t')
                  ->where('b.id_planner = ?', $id)
                  ->orderBy('p.date_begin');
        return $q->execute();
    }
}