<?php

/**
 * ContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContactTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contact');
    }
    
    public function getLastContacts($status = 'New')
    {
      $q = $this->createQuery('p')
                ->where('p.status = ?', $status)
                ->orderBy('p.id asc');
      return $q->execute();
    }
}