<?php

/**
 * ExtraCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtraCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExtraCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExtraCategory');
    }
}