<?php

/**
 * ExtraActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtraActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExtraActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExtraActivity');
    }
}