<?php

/**
 * ExtraReservedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExtraReservedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExtraReservedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExtraReserved');
    }
}