<?php

/**
 * HighlightActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HighlightActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HighlightActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HighlightActivity');
    }
    
    public function findAllWithTranslation()
    {
      $q = $this->createQuery('a')
              ->leftJoin('a.Translation t');
      return $q->execute();
    }
    
    public function getAll($lang)
    {
      $q = $this->createQuery('a')
              ->leftJoin('a.Translation t')
              ->where('t.lang = ?', $lang)
              ->andWhere('t.activity != 0')
              ->orderBy('a.number ASC');
      return $q->execute();
    }
}