<?php

/**
 * Image
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Image extends BaseImage
{
  public function generatePathFilename(sfValidatedFile $file)
  {
    $dir = sfConfig::get('sf_upload_dir') . DIRECTORY_SEPARATOR. 'photos' .DIRECTORY_SEPARATOR;
    $originalFile = str_replace($file->getOriginalExtension(), '', $file->getOriginalName());
    $destFile = $originalFile.'_act'.$file->getOriginalExtension();
    if (!file_exists($dir.$destFile))
      return $destFile;
    $nb = 1;
    while (file_exists($dir.$destFile)) {
        $destFile = $originalFile.'_act'.$nb.$file->getOriginalExtension();
        $nb++;
    }
    return $destFile;
  }
}