<?php

/**
 * Langues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Langues extends BaseLangues
{
  function __toString()
  {
    return $this->getCountry();
  }
}