<?php

/**
 * LanguesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LanguesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LanguesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Langues');
    }
    
    public function getIsos()
    {
        $q = $this->createQuery('l')
                ->select('l.iso');
        return $q->execute();
    }
    
    public function getAll()
    {
        $q = $this->createQuery('l');
        return $q->execute();
    }
}