<?php

/**
 * LanguesMoneyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LanguesMoneyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LanguesMoneyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LanguesMoney');
    }
}