<?php

/**
 * PlannerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlannerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlannerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Planner');
    }
    
    public function getLastPlanner($status = 'New')
    {
      $q = $this->createQuery('p')
                ->leftJoin('p.Booking b')
                ->leftJoin('p.User c')
                ->select('c.username as name')
                ->addSelect('p.status as status')
                ->where('p.status = ?', $status)
                ->andWhere('b.id_client = c.id')
                ->orderBy('p.date_begin');
      return $q->execute();
    }
    
    public function getAll()
    {
        $q = $this->createQuery('p')
                  ->leftJoin('p.Booking b')
                  ->leftJoin('p.User c')
                  ->where('b.id_client = c.id')
                  ->orderBy('p.date_begin');
        return $q->execute();
    }
    
    public function getByIdClient($id)
    {
      $q = $this->createQuery('p')
                ->leftJoin('p.Booking b')
                ->leftJoin('p.User c')
                ->where('b.id_client = c.id')
                ->andWhere('c.id = ?', $id)
                ->orderBy('p.date_begin');
      return $q->execute();
    }
    
    public function getByIdEmployee($id)
    {
      $q = $this->createQuery('p')
                ->leftJoin('p.Booking b')
                ->leftJoin('p.User c')
                ->where('b.id_client = c.id')
                ->andWhere('p.id_employee = ?', $id)
                ->orderBy('p.date_begin');
      return $q->execute();
    }
    
    public function getByIdActivity($id)
    {
      $q = $this->createQuery('p')
                ->leftJoin('p.Booking b')
                ->leftJoin('p.User c')
                ->where('b.id_client = c.id')
                ->andWhere('b.id_activity = ?', $id)
                ->orderBy('p.date_begin');
      return $q->execute();
    }
}