<?php

/**
 * SliderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SliderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SliderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Slider');
    }
    
    public function getAllByPosition($order = 'asc') {

      $q = $this->createQuery('s')
                 ->where('s.active = true')
                 ->orderBy("s.position $order");
      return $q->execute();
    }
    
    public function getAllByPositionWithActivity($lang, $order = 'asc') {

      $q = $this->createQuery('s')
                ->leftJoin('s.Activity a')
                ->leftJoin('a.Translation t')
                ->select('s.*, a.*, t.*')
                ->where('s.active = true')
                ->andWhere('s.lang = ?', $lang)
                ->orderBy("s.position $order");
      return $q->execute();
    }
    
    public function getLastPosition($lang) {

      $reg = $this->createQuery('s')
                ->where('s.active = true')
                ->andWhere('s.lang = ?', $lang)
                ->orderBy("s.position DESC") 
                ->fetchOne();
      if ($reg)
        return $reg->position;
      return 0;
   }

   public function getByPosition($position, $lang) {

      $reg = $this->createQuery('s')
                 ->where('s.position = ?', $position)
                 ->andWhere('s.active = true')
                 ->andWhere('s.lang = ?', $lang)
                 ->fetchOne();
      return $reg;
   }
}