<?php

/**
 * SlidesActivityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlidesActivityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlidesActivityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SlidesActivity');
    }
    
    public function getAllByPosition($idObject, $objectType, $order = 'asc') {

      $q = $this->createQuery('s')
                 ->where('s.active = true')
                 ->andWhere('s.id_object = ?', $idObject)
                 ->andWhere('s.type_object = ?', $objectType)
                 ->orderBy("s.position $order");
      return $q->execute();
    }
    
    public function getLastPosition($idObject, $objectType) {

      $reg = $this->createQuery('s')
                ->where('s.active = true')
                ->andWhere('s.id_object = ?', $idObject)
                ->andWhere('s.type_object = ?', $objectType)
                ->orderBy("s.position DESC") 
                ->fetchOne();
      if ($reg)
        return $reg->position;
      return 0;
   }

   public function getByPosition($position, $idObject, $objectType) {

      $reg = $this->createQuery('s')
                 ->where('s.position = ?', $position)
                 ->andWhere('s.active = true')
                 ->andWhere('s.id_object = ?', $idObject)
                 ->andWhere('s.type_object = ?', $objectType)
                 ->fetchOne();
      return $reg;
   }
}