<?php

/**
 * TransUnit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    stag
 * @subpackage model
 * @author     Rainmaker
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TransUnit extends BaseTransUnit
{
  public function preInsert($event)
  {
    $this->date_added = time();
    $this->translated = false;
    $this->preUpdate($event);
  }

  public function preUpdate($event)
  {
    $this->date_modified = time();
    $this->translated = (trim($this->target)) ? 1 : 0;
    //$this->target = utf8_encode($this->target);

    if(sfContext::hasInstance())
    {
      $user = sfContext::getInstance()->getUser();
      $this->author = ($user->isAuthenticated()) ? $user->getGuardUser()->username : 'anonymous';
    }
    else
    {
      $this->author = 'system';
    }

    $this->Catalogue->date_modified = time();
    $this->Catalogue->save();
  }
}
