#generator:
#  class: sfDoctrineGenerator
#  param:
#    model_class:           Informations
#    theme:                 stagAdmin
#    non_verbose_templates: true
#    with_show:             false
#    singular:              ~
#    plural:                ~
#    route_prefix:          informations
#    with_doctrine_route:   true
#    actions_base_class:    sfActions
#    css:                   nothing
#
#    config:
#      actions: ~
#      fields:  ~
#      list:
#        display:           [name, value]
#      filter:  ~
#      form:    ~
#      edit:    ~
#      new:     ~
