# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  recaptcha:
    public_key:   6LemFsUSAAAAAANSLU3bhPTOpES9QcRk2BC_SJsm
    private_key:	6LemFsUSAAAAALrQcJFhoj3zSIZUu4PiohxnBc5c
    
  doAuth:
    activation: false
    remember_cookie_name: StagRemember
    email_from: stag@rainmaker.lv
  doAuth_email:
    from: stag@rainmaker.lv
