generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Activity
    theme:                 stagAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          activity
    with_doctrine_route:   true
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions: ~
      fields:  ~
      list:
        display:           [ActivityCategory, name]
        object_actions:
          Photos:          ~ 
          Videos:          ~ 
          Sliders:         ~
          _edit: ~
          _delete: ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
