newSuccess:
  layout: layout-popup
editSuccess:
  layout: layout-popup
deleteSuccess:
  layout: layout-popup

#custom
ListPhotosSuccess:
  layout: layout-popup
ListSlidersSuccess:
  layout: layout-popup
ListVideosSuccess:
  layout: layout-popup
