# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  stag:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=stag
      username: root
      password: root
