<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version5 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('trans_unit', 'trans_unit_cat_id_catalogue_cat_id', array(
             'name' => 'trans_unit_cat_id_catalogue_cat_id',
             'local' => 'cat_id',
             'foreign' => 'cat_id',
             'foreignTable' => 'catalogue',
             ));
        $this->addIndex('trans_unit', 'trans_unit_cat_id', array(
             'fields' => 
             array(
              0 => 'cat_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('trans_unit', 'trans_unit_cat_id_catalogue_cat_id');
        $this->removeIndex('trans_unit', 'trans_unit_cat_id', array(
             'fields' => 
             array(
              0 => 'cat_id',
             ),
             ));
    }
}