<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version20 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('activity_price_translation', 'activity_price_translation_id_activity_price_id', array(
             'name' => 'activity_price_translation_id_activity_price_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'activity_price',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('activity_price_translation', 'activity_price_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('activity_price_translation', 'activity_price_translation_id_activity_price_id');
        $this->removeIndex('activity_price_translation', 'activity_price_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}