<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('langues', 'money_name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('langues', 'money_curr', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('langues', 'money_name');
        $this->removeColumn('langues', 'money_curr');
    }
}