<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('booking', 'status', 'enum', '', array(
             'values' => 
             array(
              0 => 'New',
              1 => 'InProgess',
              2 => 'Closed',
             ),
             'notnull' => '1',
             ));
        $this->changeColumn('planner', 'status', 'enum', '', array(
             'values' => 
             array(
              0 => 'New',
              1 => 'InProgess',
              2 => 'Closed',
             ),
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}