<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('planner', 'id_activity');
    }

    public function down()
    {
        $this->addColumn('planner', 'id_activity', 'integer', '8', array(
             ));
    }
}