<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('langues', 'money_name', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('langues', 'money_curr', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}