<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('langues_money', 'langues_money_langues_id_langues_id', array(
             'name' => 'langues_money_langues_id_langues_id',
             'local' => 'langues_id',
             'foreign' => 'id',
             'foreignTable' => 'langues',
             ));
        $this->createForeignKey('langues_money', 'langues_money_money_id_money_id', array(
             'name' => 'langues_money_money_id_money_id',
             'local' => 'money_id',
             'foreign' => 'id',
             'foreignTable' => 'money',
             ));
        $this->addIndex('langues_money', 'langues_money_langues_id', array(
             'fields' => 
             array(
              0 => 'langues_id',
             ),
             ));
        $this->addIndex('langues_money', 'langues_money_money_id', array(
             'fields' => 
             array(
              0 => 'money_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('langues_money', 'langues_money_langues_id_langues_id');
        $this->dropForeignKey('langues_money', 'langues_money_money_id_money_id');
        $this->removeIndex('langues_money', 'langues_money_langues_id', array(
             'fields' => 
             array(
              0 => 'langues_id',
             ),
             ));
        $this->removeIndex('langues_money', 'langues_money_money_id', array(
             'fields' => 
             array(
              0 => 'money_id',
             ),
             ));
    }
}