<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('comment', 'comment_id_activity_activity_id', array(
             'name' => 'comment_id_activity_activity_id',
             'local' => 'id_activity',
             'foreign' => 'id',
             'foreignTable' => 'activity',
             ));
        $this->createForeignKey('comment', 'comment_id_client_client_id', array(
             'name' => 'comment_id_client_client_id',
             'local' => 'id_client',
             'foreign' => 'id',
             'foreignTable' => 'client',
             ));
        $this->addIndex('comment', 'comment_id_activity', array(
             'fields' => 
             array(
              0 => 'id_activity',
             ),
             ));
        $this->addIndex('comment', 'comment_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('comment', 'comment_id_activity_activity_id');
        $this->dropForeignKey('comment', 'comment_id_client_client_id');
        $this->removeIndex('comment', 'comment_id_activity', array(
             'fields' => 
             array(
              0 => 'id_activity',
             ),
             ));
        $this->removeIndex('comment', 'comment_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
    }
}