<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version45 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('lexique', 'id_lexique', 'integer', '8', array(
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->changeColumn('lexique_translation', 'id_lexique', 'integer', '8', array(
             'primary' => '1',
             ));
    }

    public function down()
    {

    }
}