<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version35 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('highlight_activity', 'highlight_activity_id_activity_activity_id', array(
             'name' => 'highlight_activity_id_activity_activity_id',
             'local' => 'id_activity',
             'foreign' => 'id',
             'foreignTable' => 'activity',
             ));
        $this->addIndex('highlight_activity', 'highlight_activity_id_activity', array(
             'fields' => 
             array(
              0 => 'id_activity',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('highlight_activity', 'highlight_activity_id_activity_activity_id');
        $this->removeIndex('highlight_activity', 'highlight_activity_id_activity', array(
             'fields' => 
             array(
              0 => 'id_activity',
             ),
             ));
    }
}