<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version42 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('slider_translation');
        $this->addColumn('slider', 'image', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('slider', 'title', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->addColumn('slider', 'position', 'integer', '8', array(
             'default' => '0',
             ));
        $this->addColumn('slider', 'active', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->createTable('slider_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'image' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'position' => 
             array(
              'type' => 'integer',
              'default' => '0',
              'length' => '8',
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'INNODB',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('slider', 'image');
        $this->removeColumn('slider', 'title');
        $this->removeColumn('slider', 'position');
        $this->removeColumn('slider', 'active');
    }
}