<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version69 extends Doctrine_Migration_Base
{
    public function up()
    {

        $this->createForeignKey('booking', 'booking_id_client_user_id', array(
             'name' => 'booking_id_client_user_id',
             'local' => 'id_client',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('card', 'card_id_client_user_id', array(
             'name' => 'card_id_client_user_id',
             'local' => 'id_client',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('planner', 'planner_id_client_user_id', array(
             'name' => 'planner_id_client_user_id',
             'local' => 'id_client',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->createForeignKey('review', 'review_id_client_user_id', array(
             'name' => 'review_id_client_user_id',
             'local' => 'id_client',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
    }

    public function down()
    {
        $this->dropForeignKey('booking', 'booking_id_client_user_id');
        $this->dropForeignKey('card', 'card_id_client_user_id');
        $this->dropForeignKey('planner', 'planner_id_client_user_id');
        $this->dropForeignKey('review', 'review_id_client_user_id');
        $this->removeIndex('booking', 'booking_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
        $this->removeIndex('card', 'card_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
        $this->removeIndex('planner', 'planner_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
        $this->removeIndex('review', 'review_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
    }
}