<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version46 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('lexique', 'id_lexique');
        $this->removeColumn('lexique_translation', 'id_lexique');
        $this->addColumn('lexique', 'id', 'integer', '8', array(
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->addColumn('lexique_translation', 'id', 'integer', '8', array(
             'primary' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('lexique', 'id_lexique', 'integer', '8', array(
             'primary' => '1',
             'autoincrement' => '1',
             ));
        $this->addColumn('lexique_translation', 'id_lexique', 'integer', '8', array(
             'primary' => '1',
             ));
        $this->removeColumn('lexique', 'id');
        $this->removeColumn('lexique_translation', 'id');
    }
}