<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version38 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('planner', 'id_employee', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('planner', 'id_employee');
    }
}