<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version55 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('review', 'valide', 'boolean', '25', array(
             'default' => '0',
             ));
        $this->addColumn('review', 'del', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('review', 'valide');
        $this->removeColumn('review', 'del');
    }
}