<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version34 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('highlight_activity_translation', 'activity');
        $this->addColumn('highlight_activity', 'id_activity', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('highlight_activity_translation', 'activity', 'integer', '8', array(
             ));
        $this->removeColumn('highlight_activity', 'id_activity');
    }
}