<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('planner', 'id_client', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}