<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version63 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('bonuspartner', 'bonuspartner_id_partner_partners_id', array(
             'name' => 'bonuspartner_id_partner_partners_id',
             'local' => 'id_partner',
             'foreign' => 'id',
             'foreignTable' => 'partners',
             ));
        $this->addIndex('bonuspartner', 'bonuspartner_id_partner', array(
             'fields' => 
             array(
              0 => 'id_partner',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('bonuspartner', 'bonuspartner_id_partner_partners_id');
        $this->removeIndex('bonuspartner', 'bonuspartner_id_partner', array(
             'fields' => 
             array(
              0 => 'id_partner',
             ),
             ));
    }
}