<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version66 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'username' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '128',
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'unique' => '1',
              'length' => '128',
             ),
             'salt' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'password' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'is_active' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'is_super_admin' => 
             array(
              'type' => 'boolean',
              'default' => '0',
              'length' => '25',
             ),
             'last_login' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'indexes' => 
             array(
              'name_idx' => 
              array(
              'fields' => 
              array(
               0 => 'username',
              ),
              'unique' => '1',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('user_activation_code', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'code' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('booking', 'booking_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
        $this->addIndex('card', 'card_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
        $this->addIndex('planner', 'planner_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
        $this->addIndex('review', 'review_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('user');
        $this->dropTable('user_activation_code');
    }
}