<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version60 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('video', 'content', 'string', '65355', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}