<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version56 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('review', 'image', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('review', 'image');
    }
}