<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version47 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('lexique_translation', 'lexique_translation_id_lexique_lexique_id_lexique');
        $this->createForeignKey('lexique_translation', 'lexique_translation_id_lexique_id', array(
             'name' => 'lexique_translation_id_lexique_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'lexique',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('lexique_translation', 'lexique_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('lexique_translation', 'lexique_translation_id_lexique_lexique_id_lexique', array(
             'name' => 'lexique_translation_id_lexique_lexique_id_lexique',
             'local' => 'id_lexique',
             'foreign' => 'id_lexique',
             'foreignTable' => 'lexique',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->dropForeignKey('lexique_translation', 'lexique_translation_id_lexique_id');
        $this->removeIndex('lexique_translation', 'lexique_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}