<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version64 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('planner', 'submit_date', 'date', '25', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('planner', 'submit_date');
    }
}