<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version48 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('activity', 'image', 'string', '255', array(
             ));
        $this->addColumn('activity_category', 'image', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('activity', 'image');
        $this->removeColumn('activity_category', 'image');
    }
}