<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version39 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('planner', 'planner_id_employee_sf_guard_user_id', array(
             'name' => 'planner_id_employee_sf_guard_user_id',
             'local' => 'id_employee',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->addIndex('planner', 'planner_id_employee', array(
             'fields' => 
             array(
              0 => 'id_employee',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('planner', 'planner_id_employee_sf_guard_user_id');
        $this->removeIndex('planner', 'planner_id_employee', array(
             'fields' => 
             array(
              0 => 'id_employee',
             ),
             ));
    }
}