<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version24 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('informations_translation', 'informations_translation_id_informations_id', array(
             'name' => 'informations_translation_id_informations_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'informations',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('informations_translation', 'informations_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('informations_translation', 'informations_translation_id_informations_id');
        $this->removeIndex('informations_translation', 'informations_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}