<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version41 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('slider', 'slider_id_activity_activity_id', array(
             'name' => 'slider_id_activity_activity_id',
             'local' => 'id_activity',
             'foreign' => 'id',
             'foreignTable' => 'activity',
             ));
        $this->createForeignKey('slider_translation', 'slider_translation_id_slider_id', array(
             'name' => 'slider_translation_id_slider_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'slider',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('slider', 'slider_id_activity', array(
             'fields' => 
             array(
              0 => 'id_activity',
             ),
             ));
        $this->addIndex('slider_translation', 'slider_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('slider', 'slider_id_activity_activity_id');
        $this->dropForeignKey('slider_translation', 'slider_translation_id_slider_id');
        $this->removeIndex('slider', 'slider_id_activity', array(
             'fields' => 
             array(
              0 => 'id_activity',
             ),
             ));
        $this->removeIndex('slider_translation', 'slider_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}