<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version26 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('booking', 'id_client', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('booking', 'id_activity', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->changeColumn('booking', 'id_planner', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}