<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version53 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('review', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'id_client' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '63535',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('review');
    }
}