<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version78 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('bonuspartner_translation', 'bonuspartner_translation_id_bonuspartner_id', array(
             'name' => 'bonuspartner_translation_id_bonuspartner_id',
             'local' => 'id',
             'foreign' => 'id',
             'foreignTable' => 'bonuspartner',
             'onUpdate' => 'CASCADE',
             'onDelete' => 'CASCADE',
             ));
        $this->addIndex('bonuspartner_translation', 'bonuspartner_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('bonuspartner_translation', 'bonuspartner_translation_id_bonuspartner_id');
        $this->removeIndex('bonuspartner_translation', 'bonuspartner_translation_id', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             ));
    }
}