<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version75 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('planner', 'contact_name', 'string', '', array(
             ));
        $this->addColumn('planner', 'contact_surname', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('planner', 'contact_name');
        $this->removeColumn('planner', 'contact_surname');
    }
}