<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version72 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('booking', 'nb_persons', 'integer', '8', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('booking', 'nb_persons');
    }
}