<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version79 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('bonuspartner', 'code', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}