<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version77 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('bonuspartner_translation', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'primary' => '1',
             ),
             'comment' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'lang' => 
             array(
              'fixed' => '1',
              'primary' => '1',
              'type' => 'string',
              'length' => '2',
             ),
             ), array(
             'type' => 'INNODB',
             'primary' => 
             array(
              0 => 'id',
              1 => 'lang',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->removeColumn('bonuspartner', 'comment');
    }

    public function down()
    {
        $this->dropTable('bonuspartner_translation');
        $this->addColumn('bonuspartner', 'comment', 'string', '255', array(
             'notnull' => '1',
             ));
    }
}