<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version74 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('comment', 'comment_id_client_user_id', array(
             'name' => 'comment_id_client_user_id',
             'local' => 'id_client',
             'foreign' => 'id',
             'foreignTable' => 'user',
             ));
        $this->addIndex('comment', 'comment_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('comment', 'comment_id_client_user_id');
        $this->removeIndex('comment', 'comment_id_client', array(
             'fields' => 
             array(
              0 => 'id_client',
             ),
             ));
    }
}