<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version73 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('activity', 'firstname', 'string', '255', array(
             ));
        $this->addColumn('activity', 'lastname', 'string', '255', array(
             ));
        $this->addColumn('activity', 'phone', 'string', '14', array(
             ));
        $this->addColumn('activity', 'email', 'string', '255', array(
             ));
        $this->addColumn('activity', 'address', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('activity', 'firstname');
        $this->removeColumn('activity', 'lastname');
        $this->removeColumn('activity', 'phone');
        $this->removeColumn('activity', 'email');
        $this->removeColumn('activity', 'address');
    }
}