<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/12/08 16:05:35
sfConfig::add(array(
  'app_sf_admin_dash_web_dir' => '/sfAdminDashPlugin',
  'app_sf_admin_dash_image_dir' => '/sfAdminDashPlugin/images/icons/',
  'app_sf_admin_dash_default_image' => 'config.png',
  'app_sf_admin_dash_resize_mode' => 'thumbnail',
  'app_sf_admin_dash_logout' => true,
  'app_sf_admin_dash_site' => 'My Site',
  'app_sf_admin_dash_include_path' => true,
  'app_sf_admin_dash_include_jquery_no_conflict' => false,
  'app_sf_admin_dash_login_route' => '@sf_guard_signin',
  'app_sf_admin_dash_logout_route' => '@sf_guard_signout',
  'app_recaptcha_public_key' => '6LemFsUSAAAAAANSLU3bhPTOpES9QcRk2BC_SJsm',
  'app_recaptcha_private_key' => '6LemFsUSAAAAALrQcJFhoj3zSIZUu4PiohxnBc5c',
  'app_doAuth_activation' => false,
  'app_doAuth_remember_cookie_name' => 'StagRemember',
  'app_doAuth_email_from' => 'stag@rainmaker.lv',
));
